/*系统-常量信息定义表*/
CREATE TABLE FILEMANAGER_SYS_BASE_TYPE (
  CODE_TYPE NUMBER(8)     NOT NULL,
  CODE_ID   NUMBER(8)     NOT NULL,
  CODE_NAME VARCHAR2(128) NOT NULL,
  NOTES     VARCHAR2(128),
  EXT1      NUMBER(8),
  EXT2      VARCHAR2(128),
  EXT3      VARCHAR2(128),
  CONSTRAINT FILEMANAGER_SYS_BASE_TYPE_PK PRIMARY KEY (CODE_TYPE, CODE_ID)
);

COMMENT ON COLUMN FILEMANAGER_SYS_BASE_TYPE.CODE_TYPE IS '类型编码';
COMMENT ON COLUMN FILEMANAGER_SYS_BASE_TYPE.CODE_ID IS '编号';
COMMENT ON COLUMN FILEMANAGER_SYS_BASE_TYPE.CODE_NAME IS '名称';
COMMENT ON COLUMN FILEMANAGER_SYS_BASE_TYPE.NOTES IS '注释';
COMMENT ON COLUMN FILEMANAGER_SYS_BASE_TYPE.EXT1 IS '扩展字段1';
COMMENT ON COLUMN FILEMANAGER_SYS_BASE_TYPE.EXT2 IS '扩展字段2';
COMMENT ON COLUMN FILEMANAGER_SYS_BASE_TYPE.EXT3 IS '扩展字段3';


/*实体-用户信息实体类*/
CREATE TABLE USER_INFO (
  USER_ID           NUMBER(12) CONSTRAINT USER_INFO_PK PRIMARY KEY,
  USER_NAME         VARCHAR2(32) NOT NULL,
  USER_PASSWORD     VARCHAR2(64) NOT NULL,
  USER_GENDER       NUMBER(1) CHECK (USER_GENDER IN (0, 1)),
  USER_AGE          NUMBER(3)    NOT NULL,
  COLLEGE_ID        NUMBER(8),
  MANAGER           NUMBER(1),
  MANAGER_TYPE      NUMBER(1),
  USER_ADDRESS      VARCHAR2(128) NOT NULL,,
  USER_EMAIL        VARCHAR2(32) NOT NULL,
  USER_PHONE_NUMBER NUMBER(11) NOT NULL,
  CREATE_DATE       DATE         NOT NULL,
  VALIDATA_CODE VARCHAR2(128),
  OUT_DATE      NUMBER,
  NOTES             VARCHAR2(128),
  EXT1              NUMBER(8),
  EXT2              VARCHAR2(32),
  EXT3              VARCHAR2(32),
  REC_STATUS        NUMBER(1)    NOT NULL
);

COMMENT ON COLUMN USER_INFO.USER_ID IS '用户编号';
COMMENT ON COLUMN USER_INFO.USER_NAME IS '用户名';
COMMENT ON COLUMN USER_INFO.USER_PASSWORD IS '用户密码';
COMMENT ON COLUMN USER_INFO.USER_GENDER IS '用户性别';
COMMENT ON COLUMN USER_INFO.USER_AGE IS '用户年龄';
COMMENT ON COLUMN USER_INFO.COLLEGE_ID IS '学院';
COMMENT ON COLUMN USER_INFO.MANAGER IS '管理员,0否，1是';
COMMENT ON COLUMN USER_INFO.MANAGER_TYPE IS '管理员类型，1超级管理员，2普通管理员';
COMMENT ON COLUMN USER_INFO.USER_EMAIL IS '邮箱';
COMMENT ON COLUMN USER_INFO.USER_PHONE_NUMBER IS '手机号';
COMMENT ON COLUMN USER_INFO.CREATE_DATE IS '创建日期';
COMMENT ON COLUMN USER_INFO.VALIDATA_CODE IS '有效编号,用于找回密码';
COMMENT ON COLUMN USER_INFO.OUT_DATE IS '失效时间，用于找回密码';
COMMENT ON COLUMN USER_INFO.NOTES IS '注释';
COMMENT ON COLUMN USER_INFO.EXT1 IS '扩展字段1';
COMMENT ON COLUMN USER_INFO.EXT2 IS '扩展字段2';
COMMENT ON COLUMN USER_INFO.EXT3 IS '扩展字段3';
COMMENT ON COLUMN USER_INFO.REC_STATUS IS '是否有效，1有效，0无效';

/*文件表*/
CREATE TABLE FILE_INFO (
  FILE_ID     NUMBER(12) CONSTRAINT FILE_INFO_PK PRIMARY KEY,
  COLLEGE_ID  NUMBER(8),
  USER_ID     NUMBER(12)    NOT NULL,
  FILE_NAME   VARCHAR2(128) NOT NULL,
  PATH_CODE   NUMBER(8)     NOT NULL,
  CREATE_DATE DATE          NOT NULL,
  NOTES       VARCHAR2(128),
  EXT1        NUMBER(8),
  EXT2        VARCHAR2(32),
  EXT3        VARCHAR2(32),
  REC_STATUS  NUMBER(1)     NOT NULL
);

COMMENT ON COLUMN FILE_INFO.FILE_ID IS '文件编号';
COMMENT ON COLUMN FILE_INFO.COLLEGE_ID IS '学院编号';
COMMENT ON COLUMN FILE_INFO.USER_ID IS '上传者编号';
COMMENT ON COLUMN FILE_INFO.FILE_NAME IS '文件名称';
COMMENT ON COLUMN FILE_INFO.PATH_CODE IS '文件保存路径编码';
COMMENT ON COLUMN FILE_INFO.CREATE_DATE IS '文件上传时间';
COMMENT ON COLUMN FILE_INFO.NOTES IS '注释';
COMMENT ON COLUMN FILE_INFO.EXT1 IS '扩展字段1';
COMMENT ON COLUMN FILE_INFO.EXT2 IS '扩展字段2';
COMMENT ON COLUMN FILE_INFO.EXT3 IS '扩展字段3';
COMMENT ON COLUMN FILE_INFO.REC_STATUS IS '是否有效，1有效，0无效';

CREATE TABLE FILE_COLLECTION_INFO (
  USER_ID     NUMBER(12)    NOT NULL,
  UPLOADER   VARCHAR2(32)    NOT NULL,
  FILE_ID     NUMBER(12)    NOT NULL,
  FILE_NAME   VARCHAR2(128) NOT NULL,
  COLLEGE_ID  NUMBER(8),
  CREATE_DATE DATE          NOT NULL,
  EXT1        NUMBER(8),
  EXT2        VARCHAR2(32),
  EXT3        VARCHAR2(32),
  CONSTRAINT FILE_COLLECTION_INFO_PK PRIMARY KEY (USER_ID, FILE_ID)
);

COMMENT ON COLUMN FILE_COLLECTION_INFO.USER_ID IS '用户编号';
COMMENT ON COLUMN FILE_COLLECTION_INFO.UPLOADER IS '上传者名称';
COMMENT ON COLUMN FILE_COLLECTION_INFO.FILE_ID IS '文件编号';
COMMENT ON COLUMN FILE_COLLECTION_INFO.FILE_NAME IS '文件名';
COMMENT ON COLUMN FILE_COLLECTION_INFO.COLLEGE_ID IS '学院编号';
COMMENT ON COLUMN FILE_COLLECTION_INFO.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN FILE_COLLECTION_INFO.EXT1 IS '扩展字段1';
COMMENT ON COLUMN FILE_COLLECTION_INFO.EXT2 IS '扩展字段2';
COMMENT ON COLUMN FILE_COLLECTION_INFO.EXT3 IS '扩展字段3';

/**
 * 获取序列号
 */
CREATE SEQUENCE SEQ_DONE_CODE
INCREMENT BY 1
START WITH 1
MAXVALUE 999999999;


